import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Do Bicho Brasil</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {window.location.host.split('.')[0] == 'staging' && (
        <div className={styles.header}>STAGING</div>
      )}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Do Bicho.com.br!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
